/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости сервиса и БД */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог шин с фильтрами и пагинацией
         * @description Имена фильтров совпадают с query-параметрами URL витрины.
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Реальные значения фильтров, присутствующие в каталоге
         * @description Бренды и типоразмеры, фактически имеющиеся в ассортименте города. Витрина строит из них опции сайдбара вместо статики.
         */
        get: operations["getCatalogFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Статус заказа по номеру (обратная интеграция tradesk)
         * @description Читает статус заказа ИЗ tradesk (GET /data/status?order_code=). Страница /status/ витрины. found=false — заказ не найден или tradesk-приём выключен.
         */
        get: operations["getOrderStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pickup-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Опубликованные пункты выдачи (страница /points)
         * @description Пункты выдачи заказов витрины города (city, по умолчанию spb). Контент редактируется в админке: адрес, метро, часы, бейдж-акция у каждого — свои. is_main — «основной адрес» (крупная карточка, первым).
         */
        get: operations["listPickupPoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pickup-points/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пункт выдачи по slug (отдельная страница /points/<slug>) */
        get: operations["getPickupPoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benefits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Опубликованные офферы строки «Преимущества» (главная)
         * @description Строка офферов над каталогом (BenefitsBar). Контент редактируется в админке (раздел «Преимущества»), поэтому витрина берёт его по API.
         */
        get: operations["listBenefits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Эффективная SEO-мета маршрута витрины
         * @description title/description для generateMetadata статических страниц. Значения маршрута с подстановкой дефолт-шаблона по пустым полям. Мета редактируется в админке (раздел «SEO-мета»). Контентные страницы несут мету сами.
         */
        get: operations["resolveSeo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Товар по slug */
        get: operations["getProductBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Оформление заказа
         * @description Заказ пишется в БД транзакционно со строкой outbox; воркер доставляет его в tradesk с ретраями — заказ никогда не теряется. Idempotency-key (заголовок или поле тела) защищает от даблклика «Оформить заказ».
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Заявка с формы услуги
         * @description Формы сервисных страниц (шиномонтаж, хранение, ремонт и покраска дисков). Уходит в tradesk `POST /api/request` через outbox — с типом услуги, в отличие от обратного звонка.
         */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/callbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Заявка «обратный звонок»
         * @description Попадает в tradesk (раздел «Обратный звонок») через outbox.
         */
        post: operations["createCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Season: "summer" | "winter" | "allseason";
        Product: {
            /** Format: int64 */
            id: number;
            /** @example nokian-hakkapeliitta-10p-205-55-r16 */
            slug: string;
            /**
             * @description Код товара в SelectTyres — уходит в заказ tradesk
             * @example t668559
             */
            code?: string;
            /** @example Nokian */
            brand: string;
            /** @example Hakkapeliitta 10p */
            model: string;
            /** @example Nokian Hakkapeliitta 10p 205/55 R16 */
            name: string;
            /** @example 205/55 R16 94T */
            size_label: string;
            /** @example 205 */
            width: number;
            /** @example 55 */
            profile: number;
            /** @example 16 */
            diameter: number;
            season: components["schemas"]["Season"];
            spikes: boolean;
            runflat: boolean;
            /**
             * @description Рубли за штуку
             * @example 12490
             */
            price: number;
            /** @example 16 */
            stock: number;
            /** @description Фото из SelectTyres (пусто → плейсхолдер) */
            image_url: string;
            /** @description Бейдж «Хит» (оверрайд админки) */
            badge_hit: boolean;
        };
        ProductList: {
            items: components["schemas"]["Product"][];
            total: number;
            page: number;
            per_page: number;
        };
        OrderItem: {
            slug: string;
            /**
             * @description Код товара в SelectTyres — уходит в приёмник заказа tradesk
             * @example t668559
             */
            code?: string;
            name: string;
            /** @description Рубли за штуку */
            price: number;
            /**
             * @description Шины покупают комплектами — дефолт 4
             * @default 4
             */
            qty: number;
        };
        CreateOrderInput: {
            idempotency_key?: string;
            /** @example Иван Петров */
            customer_name: string;
            /** @example +7 (921) 123-45-67 */
            phone: string;
            comment?: string;
            items: components["schemas"]["OrderItem"][];
        };
        CatalogFacets: {
            brands: string[];
            widths: number[];
            profiles: number[];
            diameters: number[];
            /** @description Топ типоразмеров по числу товаров в наличии (чипы «Популярно» в hero) */
            popular_sizes: {
                width: number;
                profile: number;
                diameter: number;
                /** @example 205/55 R16 */
                label: string;
            }[];
        };
        OrderStatus: {
            found: boolean;
            /** @example C288416 */
            code: string;
            /**
             * @description Сырой код статуса tradesk
             * @example ready
             */
            status: string;
            /** @example Готов к выдаче */
            status_text: string;
            /** @description Этап прогресса 0..4 (0 — без полосы) */
            step: number;
            /** @description Дата исполнения dd-mm-yyyy или пусто */
            date: string;
            /** @description Пункт выдачи */
            point: string;
            products: {
                name: string;
                qty: number;
                price: number;
                sum: number;
            }[];
        };
        PickupPoint: {
            /** Format: int64 */
            id: number;
            /**
             * @description URL-slug для страницы /points/<slug>
             * @example novoselov-49
             */
            slug: string;
            /** @example ул. Новосёлов, 49 */
            address: string;
            /** @example м. Ломоносовская */
            metro: string;
            /** @example 09:00–21:00 */
            hours: string;
            /**
             * @description Акция-бейдж
             * @example −15% на шиномонтаж
             */
            badge: string;
            /** @description Доп. описание пункта */
            note: string;
            /** @description Устаревший флаг центрального склада */
            is_central: boolean;
            /** @description Основной адрес (крупная карточка, первым) */
            is_main: boolean;
            /**
             * @description Город пункта
             * @example spb
             */
            city: string;
            sort_order: number;
            published: boolean;
        };
        Benefit: {
            /** Format: int64 */
            id: number;
            /**
             * @description Путь к svg-иконке
             * @example /icons/benefit-mount.svg
             */
            icon: string;
            /** @example −15% на шиномонтаж */
            title: string;
            /** @example при покупке шин */
            note: string;
            /**
             * @description Ссылка на страницу сервиса (пусто — не кликабелен)
             * @example /mounting/
             */
            href: string;
            sort_order: number;
            published: boolean;
        };
        SeoResolved: {
            /** @example Шины — купить в Санкт-Петербурге | TireStock */
            title: string;
            description: string;
        };
        RequestInput: {
            /** @example Иван */
            name?: string;
            /** @example +7 (921) 123-45-67 */
            phone: string;
            /**
             * @description Тип заявки — уходит в tradesk отдельным полем
             * @example Шиномонтаж
             */
            type: string;
            comment?: string;
        };
        CallbackInput: {
            /** @example Иван */
            name?: string;
            /** @example +7 (921) 123-45-67 */
            phone: string;
            comment?: string;
        };
        ErrorBody: {
            error: {
                /** @description Стабильный строковый код: validation_failed, not_found, internal_error, db_unavailable */
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Ошибка в едином формате */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис и БД в порядке */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /** @description Текстовый поиск по названию/бренду/модели */
                q?: string;
                /** @description Ширина, мм (205) */
                width?: number;
                /** @description Профиль, % (55) */
                profile?: number;
                /** @description Диаметр, дюймы (16) */
                diameter?: number;
                season?: components["schemas"]["Season"];
                /** @description Бренд (Nokian) */
                brand?: string;
                /** @description Цена от, ₽ */
                price_min?: number;
                /** @description Цена до, ₽ */
                price_max?: number;
                /** @description Шипы */
                spikes?: boolean;
                /** @description RunFlat */
                runflat?: boolean;
                /** @description Сортировка (по умолчанию — наличие + релевантность) */
                sort?: "price_asc" | "price_desc" | "name";
                /** @description Город (мультигород): цена/остаток и ассортимент по городу */
                city?: "spb" | "msk";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница каталога */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getCatalogFacets: {
        parameters: {
            query?: {
                /** @description Город */
                city?: "spb" | "msk";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Фасеты каталога */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFacets"];
                };
            };
        };
    };
    getOrderStatus: {
        parameters: {
            query: {
                /** @description Номер заказа */
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Статус заказа (или found=false) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatus"];
                };
            };
        };
    };
    listPickupPoints: {
        parameters: {
            query?: {
                /** @description Город пунктов (spb|msk) */
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пункты в порядке вывода (основные первыми) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PickupPoint"][];
                    };
                };
            };
        };
    };
    getPickupPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пункт выдачи */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickupPoint"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listBenefits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Офферы в порядке вывода */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Benefit"][];
                    };
                };
            };
        };
    };
    resolveSeo: {
        parameters: {
            query?: {
                /** @description Маршрут, напр. /catalog (пусто → /) */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Эффективная мета */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeoResolved"];
                };
            };
        };
    };
    getProductBySlug: {
        parameters: {
            query?: {
                /** @description Город: цена/остаток по городу; нет оффера → 404 */
                city?: "spb" | "msk";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Заказ принят */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        order_id: number;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestInput"];
            };
        };
        responses: {
            /** @description Заявка принята */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallbackInput"];
            };
        };
        responses: {
            /** @description Заявка принята */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
}
