/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости сервиса и БД */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог шин с фильтрами и пагинацией
         * @description Имена фильтров совпадают с query-параметрами URL витрины.
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Товар по slug */
        get: operations["getProductBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Оформление заказа
         * @description Заказ пишется в БД транзакционно со строкой outbox; воркер доставляет его в tradesk с ретраями — заказ никогда не теряется. Idempotency-key (заголовок или поле тела) защищает от даблклика «Оформить заказ».
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/callbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Заявка «обратный звонок»
         * @description Попадает в tradesk (раздел «Обратный звонок») через outbox.
         */
        post: operations["createCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Season: "summer" | "winter" | "allseason";
        Product: {
            /** Format: int64 */
            id: number;
            /** @example nokian-hakkapeliitta-10p-205-55-r16 */
            slug: string;
            /** @example Nokian */
            brand: string;
            /** @example Hakkapeliitta 10p */
            model: string;
            /** @example Nokian Hakkapeliitta 10p 205/55 R16 */
            name: string;
            /** @example 205/55 R16 94T */
            size_label: string;
            /** @example 205 */
            width: number;
            /** @example 55 */
            profile: number;
            /** @example 16 */
            diameter: number;
            season: components["schemas"]["Season"];
            spikes: boolean;
            runflat: boolean;
            /**
             * @description Рубли за штуку
             * @example 12490
             */
            price: number;
            /** @example 16 */
            stock: number;
            /** @description Фото из SelectTyres (пусто → плейсхолдер) */
            image_url: string;
            /** @description Бейдж «Хит» (оверрайд админки) */
            badge_hit: boolean;
        };
        ProductList: {
            items: components["schemas"]["Product"][];
            total: number;
            page: number;
            per_page: number;
        };
        OrderItem: {
            slug: string;
            name: string;
            /** @description Рубли за штуку */
            price: number;
            /**
             * @description Шины покупают комплектами — дефолт 4
             * @default 4
             */
            qty: number;
        };
        CreateOrderInput: {
            idempotency_key?: string;
            /** @example Иван Петров */
            customer_name: string;
            /** @example +7 (921) 123-45-67 */
            phone: string;
            comment?: string;
            items: components["schemas"]["OrderItem"][];
        };
        CallbackInput: {
            /** @example Иван */
            name?: string;
            /** @example +7 (921) 123-45-67 */
            phone: string;
            comment?: string;
        };
        ErrorBody: {
            error: {
                /** @description Стабильный строковый код: validation_failed, not_found, internal_error, db_unavailable */
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Ошибка в едином формате */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис и БД в порядке */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /** @description Текстовый поиск по названию/бренду/модели */
                q?: string;
                /** @description Ширина, мм (205) */
                width?: number;
                /** @description Профиль, % (55) */
                profile?: number;
                /** @description Диаметр, дюймы (16) */
                diameter?: number;
                season?: components["schemas"]["Season"];
                /** @description Бренд (Nokian) */
                brand?: string;
                /** @description Цена от, ₽ */
                price_min?: number;
                /** @description Цена до, ₽ */
                price_max?: number;
                /** @description Шипы */
                spikes?: boolean;
                /** @description RunFlat */
                runflat?: boolean;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница каталога */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getProductBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Заказ принят */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        order_id: number;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallbackInput"];
            };
        };
        responses: {
            /** @description Заявка принята */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
}
