// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, kind, payload, attempts
FROM outbox
WHERE status = 'pending' AND next_retry_at <= now()
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimOutboxRow struct {
	ID       int64
	Kind     string
	Payload  []byte
	Attempts int32
}

func (q *Queries) ClaimOutbox(ctx context.Context, limit int32) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderIDByIdempotencyKey = `-- name: GetOrderIDByIdempotencyKey :one
SELECT id FROM orders WHERE idempotency_key = $1
`

func (q *Queries) GetOrderIDByIdempotencyKey(ctx context.Context, idempotencyKey string) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderIDByIdempotencyKey, idempotencyKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOutbox = `-- name: GetOutbox :one
SELECT id, kind, payload, status, attempts, next_retry_at, last_error
FROM outbox
WHERE id = $1
`

type GetOutboxRow struct {
	ID          int64
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int32
	NextRetryAt pgtype.Timestamptz
	LastError   string
}

func (q *Queries) GetOutbox(ctx context.Context, id int64) (GetOutboxRow, error) {
	row := q.db.QueryRow(ctx, getOutbox, id)
	var i GetOutboxRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (idempotency_key, customer_name, phone, comment, items, total)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertOrderParams struct {
	IdempotencyKey string
	CustomerName   string
	Phone          string
	Comment        string
	Items          []byte
	Total          int32
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.IdempotencyKey,
		arg.CustomerName,
		arg.Phone,
		arg.Comment,
		arg.Items,
		arg.Total,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (kind, payload)
VALUES ($1, $2)
RETURNING id
`

type InsertOutboxParams struct {
	Kind    string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutbox, arg.Kind, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox
SET status = 'delivered', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, id)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET status = 'failed', attempts = attempts + 1, last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const rescheduleOutbox = `-- name: RescheduleOutbox :exec
UPDATE outbox
SET attempts = attempts + 1, next_retry_at = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type RescheduleOutboxParams struct {
	ID          int64
	NextRetryAt pgtype.Timestamptz
	LastError   string
}

func (q *Queries) RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutbox, arg.ID, arg.NextRetryAt, arg.LastError)
	return err
}
