// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, kind, payload, attempts
FROM outbox
WHERE status = 'pending' AND next_retry_at <= now()
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimOutboxRow struct {
	ID       int64
	Kind     string
	Payload  []byte
	Attempts int32
}

func (q *Queries) ClaimOutbox(ctx context.Context, limit int32) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdminUsers = `-- name: CountAdminUsers :one

SELECT count(*) FROM admin_users
`

// ── Пользователи / сессии ──────────────────────────────────────────────────
func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSyncedProducts = `-- name: CountSyncedProducts :one
SELECT count(*) FROM products WHERE code <> ''
`

func (q *Queries) CountSyncedProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSyncedProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBenefit = `-- name: CreateBenefit :one
INSERT INTO benefits (icon, title, note, href, sort_order, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, icon, title, note, href, sort_order, published, updated_by, updated_at
`

type CreateBenefitParams struct {
	Icon      string
	Title     string
	Note      string
	Href      string
	SortOrder int32
	UpdatedBy string
}

type CreateBenefitRow struct {
	ID        int64
	Icon      string
	Title     string
	Note      string
	Href      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateBenefit(ctx context.Context, arg CreateBenefitParams) (CreateBenefitRow, error) {
	row := q.db.QueryRow(ctx, createBenefit,
		arg.Icon,
		arg.Title,
		arg.Note,
		arg.Href,
		arg.SortOrder,
		arg.UpdatedBy,
	)
	var i CreateBenefitRow
	err := row.Scan(
		&i.ID,
		&i.Icon,
		&i.Title,
		&i.Note,
		&i.Href,
		&i.SortOrder,
		&i.Published,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createContentPage = `-- name: CreateContentPage :one
INSERT INTO content_pages (slug, title, updated_by)
VALUES ($1, $2, $3)
RETURNING id, slug, title, body, meta_title, meta_description,
          published, indexed, system, updated_by, updated_at
`

type CreateContentPageParams struct {
	Slug      string
	Title     string
	UpdatedBy string
}

type CreateContentPageRow struct {
	ID              int64
	Slug            string
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	Published       bool
	Indexed         bool
	System          bool
	UpdatedBy       string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateContentPage(ctx context.Context, arg CreateContentPageParams) (CreateContentPageRow, error) {
	row := q.db.QueryRow(ctx, createContentPage, arg.Slug, arg.Title, arg.UpdatedBy)
	var i CreateContentPageRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Published,
		&i.Indexed,
		&i.System,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createPickupPoint = `-- name: CreatePickupPoint :one
INSERT INTO pickup_points (slug, address, metro, hours, badge, note, is_central, is_main, city, sort_order, published, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, slug, address, metro, hours, badge, note, is_central, is_main, city, sort_order, published, updated_by, updated_at
`

type CreatePickupPointParams struct {
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
}

type CreatePickupPointRow struct {
	ID        int64
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePickupPoint(ctx context.Context, arg CreatePickupPointParams) (CreatePickupPointRow, error) {
	row := q.db.QueryRow(ctx, createPickupPoint,
		arg.Slug,
		arg.Address,
		arg.Metro,
		arg.Hours,
		arg.Badge,
		arg.Note,
		arg.IsCentral,
		arg.IsMain,
		arg.City,
		arg.SortOrder,
		arg.Published,
		arg.UpdatedBy,
	)
	var i CreatePickupPointRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Address,
		&i.Metro,
		&i.Hours,
		&i.Badge,
		&i.Note,
		&i.IsCentral,
		&i.IsMain,
		&i.City,
		&i.SortOrder,
		&i.Published,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO admin_sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteBenefit = `-- name: DeleteBenefit :exec
DELETE FROM benefits WHERE id = $1
`

func (q *Queries) DeleteBenefit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBenefit, id)
	return err
}

const deleteContentPage = `-- name: DeleteContentPage :exec
DELETE FROM content_pages WHERE id = $1
`

func (q *Queries) DeleteContentPage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteContentPage, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM admin_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deletePickupPoint = `-- name: DeletePickupPoint :exec
DELETE FROM pickup_points WHERE id = $1
`

func (q *Queries) DeletePickupPoint(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePickupPoint, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM admin_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getAdminOrder = `-- name: GetAdminOrder :one
SELECT
    o.id,
    o.customer_name,
    o.phone,
    o.comment,
    o.items,
    o.total,
    o.created_at,
    COALESCE(ob.status, 'pending') AS delivery_status,
    COALESCE(ob.attempts, 0)       AS attempts,
    COALESCE(ob.last_error, '')    AS last_error,
    COALESCE(ob.result, '')        AS tradesk_number
FROM orders o
LEFT JOIN outbox ob
    ON ob.kind = 'order' AND (ob.payload->>'order_id')::bigint = o.id
WHERE o.id = $1
`

type GetAdminOrderRow struct {
	ID             int64
	CustomerName   string
	Phone          string
	Comment        string
	Items          []byte
	Total          int32
	CreatedAt      pgtype.Timestamptz
	DeliveryStatus string
	Attempts       int32
	LastError      string
	TradeskNumber  string
}

// Один заказ с деталями (состав, комментарий) + статус доставки в tradesk.
func (q *Queries) GetAdminOrder(ctx context.Context, id int64) (GetAdminOrderRow, error) {
	row := q.db.QueryRow(ctx, getAdminOrder, id)
	var i GetAdminOrderRow
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.Phone,
		&i.Comment,
		&i.Items,
		&i.Total,
		&i.CreatedAt,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.LastError,
		&i.TradeskNumber,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, display_name
FROM admin_users
WHERE username = $1
`

type GetAdminUserByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (GetAdminUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByUsername, username)
	var i GetAdminUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
	)
	return i, err
}

const getBenefit = `-- name: GetBenefit :one
SELECT id, icon, title, note, href, sort_order, published, updated_by, updated_at
FROM benefits WHERE id = $1
`

type GetBenefitRow struct {
	ID        int64
	Icon      string
	Title     string
	Note      string
	Href      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetBenefit(ctx context.Context, id int64) (GetBenefitRow, error) {
	row := q.db.QueryRow(ctx, getBenefit, id)
	var i GetBenefitRow
	err := row.Scan(
		&i.ID,
		&i.Icon,
		&i.Title,
		&i.Note,
		&i.Href,
		&i.SortOrder,
		&i.Published,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogProductBySlug = `-- name: GetCatalogProductBySlug :one
SELECT
    p.id, p.slug, p.code, p.brand, p.model, p.name, p.size_label,
    p.width, p.profile, p.diameter, p.season, p.spikes, p.runflat,
    po.price, po.stock,
    COALESCE(NULLIF(p.image_clean_url, ''), p.image_url) AS image_url,
    COALESCE(o.badge_hit, false) AS badge_hit
FROM products p
JOIN product_offers po ON po.product_code = p.code AND po.city = $2
LEFT JOIN product_overrides o ON o.slug = p.slug
WHERE p.slug = $1 AND COALESCE(o.hidden, false) = false
`

type GetCatalogProductBySlugParams struct {
	Slug string
	City string
}

type GetCatalogProductBySlugRow struct {
	ID        int64
	Slug      string
	Code      string
	Brand     string
	Model     string
	Name      string
	SizeLabel string
	Width     int32
	Profile   int32
	Diameter  int32
	Season    string
	Spikes    bool
	Runflat   bool
	Price     int64
	Stock     int32
	ImageUrl  string
	BadgeHit  bool
}

// City-aware: цена/остаток из оффера города ($2). Товар без оффера в городе → нет строки.
func (q *Queries) GetCatalogProductBySlug(ctx context.Context, arg GetCatalogProductBySlugParams) (GetCatalogProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCatalogProductBySlug, arg.Slug, arg.City)
	var i GetCatalogProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Brand,
		&i.Model,
		&i.Name,
		&i.SizeLabel,
		&i.Width,
		&i.Profile,
		&i.Diameter,
		&i.Season,
		&i.Spikes,
		&i.Runflat,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.BadgeHit,
	)
	return i, err
}

const getContentPage = `-- name: GetContentPage :one
SELECT id, slug, title, body, meta_title, meta_description,
       published, indexed, system, updated_by, updated_at
FROM content_pages WHERE id = $1
`

type GetContentPageRow struct {
	ID              int64
	Slug            string
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	Published       bool
	Indexed         bool
	System          bool
	UpdatedBy       string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetContentPage(ctx context.Context, id int64) (GetContentPageRow, error) {
	row := q.db.QueryRow(ctx, getContentPage, id)
	var i GetContentPageRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Published,
		&i.Indexed,
		&i.System,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentPageBySlug = `-- name: GetContentPageBySlug :one
SELECT id, slug, title, body, meta_title, meta_description,
       published, indexed, system, updated_by, updated_at
FROM content_pages WHERE slug = $1
`

type GetContentPageBySlugRow struct {
	ID              int64
	Slug            string
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	Published       bool
	Indexed         bool
	System          bool
	UpdatedBy       string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetContentPageBySlug(ctx context.Context, slug string) (GetContentPageBySlugRow, error) {
	row := q.db.QueryRow(ctx, getContentPageBySlug, slug)
	var i GetContentPageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Published,
		&i.Indexed,
		&i.System,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderIDByIdempotencyKey = `-- name: GetOrderIDByIdempotencyKey :one
SELECT id FROM orders WHERE idempotency_key = $1
`

func (q *Queries) GetOrderIDByIdempotencyKey(ctx context.Context, idempotencyKey string) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderIDByIdempotencyKey, idempotencyKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOutbox = `-- name: GetOutbox :one
SELECT id, kind, payload, status, attempts, next_retry_at, last_error
FROM outbox
WHERE id = $1
`

type GetOutboxRow struct {
	ID          int64
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int32
	NextRetryAt pgtype.Timestamptz
	LastError   string
}

func (q *Queries) GetOutbox(ctx context.Context, id int64) (GetOutboxRow, error) {
	row := q.db.QueryRow(ctx, getOutbox, id)
	var i GetOutboxRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
	)
	return i, err
}

const getPickupPoint = `-- name: GetPickupPoint :one
SELECT id, slug, address, metro, hours, badge, note, is_central, is_main, city, sort_order, published, updated_by, updated_at
FROM pickup_points WHERE id = $1
`

type GetPickupPointRow struct {
	ID        int64
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetPickupPoint(ctx context.Context, id int64) (GetPickupPointRow, error) {
	row := q.db.QueryRow(ctx, getPickupPoint, id)
	var i GetPickupPointRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Address,
		&i.Metro,
		&i.Hours,
		&i.Badge,
		&i.Note,
		&i.IsCentral,
		&i.IsMain,
		&i.City,
		&i.SortOrder,
		&i.Published,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPickupPointBySlug = `-- name: GetPickupPointBySlug :one
SELECT id, slug, address, metro, hours, badge, note, is_central, is_main, city, sort_order, published, updated_by, updated_at
FROM pickup_points WHERE slug = $1 AND slug <> '' AND published = true
`

type GetPickupPointBySlugRow struct {
	ID        int64
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

// Опубликованный пункт по slug — для отдельной страницы /points/<slug>.
func (q *Queries) GetPickupPointBySlug(ctx context.Context, slug string) (GetPickupPointBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPickupPointBySlug, slug)
	var i GetPickupPointBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Address,
		&i.Metro,
		&i.Hours,
		&i.Badge,
		&i.Note,
		&i.IsCentral,
		&i.IsMain,
		&i.City,
		&i.SortOrder,
		&i.Published,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeoMeta = `-- name: GetSeoMeta :one
SELECT route, label, title, description, is_default, updated_by, updated_at
FROM seo_meta WHERE route = $1
`

func (q *Queries) GetSeoMeta(ctx context.Context, route string) (SeoMetum, error) {
	row := q.db.QueryRow(ctx, getSeoMeta, route)
	var i SeoMetum
	err := row.Scan(
		&i.Route,
		&i.Label,
		&i.Title,
		&i.Description,
		&i.IsDefault,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.display_name
FROM admin_sessions s
JOIN admin_users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID          int64
	Username    string
	DisplayName string
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(&i.ID, &i.Username, &i.DisplayName)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :one
INSERT INTO admin_users (username, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertAdminUserParams struct {
	Username     string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAdminUser, arg.Username, arg.PasswordHash, arg.DisplayName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (idempotency_key, customer_name, phone, comment, items, total)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertOrderParams struct {
	IdempotencyKey string
	CustomerName   string
	Phone          string
	Comment        string
	Items          []byte
	Total          int32
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.IdempotencyKey,
		arg.CustomerName,
		arg.Phone,
		arg.Comment,
		arg.Items,
		arg.Total,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (kind, payload)
VALUES ($1, $2)
RETURNING id
`

type InsertOutboxParams struct {
	Kind    string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutbox, arg.Kind, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBenefits = `-- name: ListBenefits :many

SELECT id, icon, title, note, href, sort_order, published, updated_by, updated_at
FROM benefits
ORDER BY sort_order, id
`

type ListBenefitsRow struct {
	ID        int64
	Icon      string
	Title     string
	Note      string
	Href      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

// Раздел «Преимущества» админки (строка офферов BenefitsBar). Правила — в сервисе.
// Все офферы для админки (любой статус), в порядке вывода.
func (q *Queries) ListBenefits(ctx context.Context) ([]ListBenefitsRow, error) {
	rows, err := q.db.Query(ctx, listBenefits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBenefitsRow
	for rows.Next() {
		var i ListBenefitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Icon,
			&i.Title,
			&i.Note,
			&i.Href,
			&i.SortOrder,
			&i.Published,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentPages = `-- name: ListContentPages :many

SELECT id, slug, title, body, meta_title, meta_description,
       published, indexed, system, updated_by, updated_at
FROM content_pages
ORDER BY published DESC, id
`

type ListContentPagesRow struct {
	ID              int64
	Slug            string
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	Published       bool
	Indexed         bool
	System          bool
	UpdatedBy       string
	UpdatedAt       pgtype.Timestamptz
}

// Контентные страницы админки. Правила блокировки — в сервисе internal/content.
func (q *Queries) ListContentPages(ctx context.Context) ([]ListContentPagesRow, error) {
	rows, err := q.db.Query(ctx, listContentPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentPagesRow
	for rows.Next() {
		var i ListContentPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Published,
			&i.Indexed,
			&i.System,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many

SELECT
    o.id,
    o.customer_name,
    o.phone,
    o.total,
    o.created_at,
    COALESCE(ob.status, 'pending') AS delivery_status,
    COALESCE(ob.attempts, 0)       AS attempts,
    COALESCE(ob.last_error, '')    AS last_error,
    COALESCE(ob.result, '')        AS tradesk_number
FROM orders o
LEFT JOIN outbox ob
    ON ob.kind = 'order' AND (ob.payload->>'order_id')::bigint = o.id
WHERE $3::text = '' OR COALESCE(ob.status, 'pending') = $3::text
ORDER BY o.id DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32
	Offset int32
	Status string
}

type ListOrdersRow struct {
	ID             int64
	CustomerName   string
	Phone          string
	Total          int32
	CreatedAt      pgtype.Timestamptz
	DeliveryStatus string
	Attempts       int32
	LastError      string
	TradeskNumber  string
}

// ── Заказы (проекция для админки: заказ + статус доставки из outbox) ─────────
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.Phone,
			&i.Total,
			&i.CreatedAt,
			&i.DeliveryStatus,
			&i.Attempts,
			&i.LastError,
			&i.TradeskNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverrides = `-- name: ListOverrides :many

SELECT slug, hidden, badge_hit FROM product_overrides
`

type ListOverridesRow struct {
	Slug     string
	Hidden   bool
	BadgeHit bool
}

// ── Оверрайды товаров ───────────────────────────────────────────────────────
func (q *Queries) ListOverrides(ctx context.Context) ([]ListOverridesRow, error) {
	rows, err := q.db.Query(ctx, listOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverridesRow
	for rows.Next() {
		var i ListOverridesRow
		if err := rows.Scan(&i.Slug, &i.Hidden, &i.BadgeHit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickupPoints = `-- name: ListPickupPoints :many

SELECT id, slug, address, metro, hours, badge, note, is_central, is_main, city, sort_order, published, updated_by, updated_at
FROM pickup_points
ORDER BY is_main DESC, sort_order, id
`

type ListPickupPointsRow struct {
	ID        int64
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

// Раздел «Пункты выдачи» админки. Правила — в сервисе internal/pickups.
// Все пункты для админки (любой статус), основные первыми, затем по порядку.
func (q *Queries) ListPickupPoints(ctx context.Context) ([]ListPickupPointsRow, error) {
	rows, err := q.db.Query(ctx, listPickupPoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPickupPointsRow
	for rows.Next() {
		var i ListPickupPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Address,
			&i.Metro,
			&i.Hours,
			&i.Badge,
			&i.Note,
			&i.IsCentral,
			&i.IsMain,
			&i.City,
			&i.SortOrder,
			&i.Published,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBenefits = `-- name: ListPublishedBenefits :many
SELECT id, icon, title, note, href, sort_order, published, updated_by, updated_at
FROM benefits
WHERE published = true
ORDER BY sort_order, id
`

type ListPublishedBenefitsRow struct {
	ID        int64
	Icon      string
	Title     string
	Note      string
	Href      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

// Опубликованные офферы для витрины.
func (q *Queries) ListPublishedBenefits(ctx context.Context) ([]ListPublishedBenefitsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedBenefits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedBenefitsRow
	for rows.Next() {
		var i ListPublishedBenefitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Icon,
			&i.Title,
			&i.Note,
			&i.Href,
			&i.SortOrder,
			&i.Published,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedByPrefix = `-- name: ListPublishedByPrefix :many
SELECT id, slug, title, body, meta_title, meta_description,
       published, indexed, system, updated_by, updated_at
FROM content_pages
WHERE published = true AND slug LIKE $1 || '%' AND slug <> $1
ORDER BY updated_at DESC, id DESC
`

type ListPublishedByPrefixRow struct {
	ID              int64
	Slug            string
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	Published       bool
	Indexed         bool
	System          bool
	UpdatedBy       string
	UpdatedAt       pgtype.Timestamptz
}

// Опубликованные страницы под префиксом URL (напр. '/news/') — для раздела-листинга.
// Сам префикс-индекс (slug = префикс) исключаем. Свежие сверху.
func (q *Queries) ListPublishedByPrefix(ctx context.Context, dollar_1 *string) ([]ListPublishedByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listPublishedByPrefix, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedByPrefixRow
	for rows.Next() {
		var i ListPublishedByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Published,
			&i.Indexed,
			&i.System,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPickupPoints = `-- name: ListPublishedPickupPoints :many
SELECT id, slug, address, metro, hours, badge, note, is_central, is_main, city, sort_order, published, updated_by, updated_at
FROM pickup_points
WHERE published = true AND city = $1
ORDER BY is_main DESC, sort_order, id
`

type ListPublishedPickupPointsRow struct {
	ID        int64
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
}

// Опубликованные пункты для витрины (по городу).
func (q *Queries) ListPublishedPickupPoints(ctx context.Context, city string) ([]ListPublishedPickupPointsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPickupPoints, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPickupPointsRow
	for rows.Next() {
		var i ListPublishedPickupPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Address,
			&i.Metro,
			&i.Hours,
			&i.Badge,
			&i.Note,
			&i.IsCentral,
			&i.IsMain,
			&i.City,
			&i.SortOrder,
			&i.Published,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeoMeta = `-- name: ListSeoMeta :many

SELECT route, label, title, description, is_default, updated_by, updated_at
FROM seo_meta
ORDER BY is_default DESC, route
`

// Раздел «SEO-мета» админки. Правила резолва (роут ∥ дефолт) — в сервисе.
// Все записи для админки; дефолт-шаблон ('*') первым.
func (q *Queries) ListSeoMeta(ctx context.Context) ([]SeoMetum, error) {
	rows, err := q.db.Query(ctx, listSeoMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoMetum
	for rows.Next() {
		var i SeoMetum
		if err := rows.Scan(
			&i.Route,
			&i.Label,
			&i.Title,
			&i.Description,
			&i.IsDefault,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox
SET status = 'delivered', result = $2, updated_at = now()
WHERE id = $1
`

type MarkOutboxDeliveredParams struct {
	ID     int64
	Result string
}

func (q *Queries) MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, arg.ID, arg.Result)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET status = 'failed', attempts = attempts + 1, last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const orderStats = `-- name: OrderStats :one
SELECT
    count(*) FILTER (WHERE o.created_at::date = now()::date)          AS today,
    count(*) FILTER (WHERE COALESCE(ob.status, 'pending') = 'pending') AS queued,
    count(*) FILTER (WHERE ob.status = 'failed')                      AS failed
FROM orders o
LEFT JOIN outbox ob
    ON ob.kind = 'order' AND (ob.payload->>'order_id')::bigint = o.id
`

type OrderStatsRow struct {
	Today  int64
	Queued int64
	Failed int64
}

func (q *Queries) OrderStats(ctx context.Context) (OrderStatsRow, error) {
	row := q.db.QueryRow(ctx, orderStats)
	var i OrderStatsRow
	err := row.Scan(&i.Today, &i.Queued, &i.Failed)
	return i, err
}

const renameContentPage = `-- name: RenameContentPage :exec
UPDATE content_pages SET slug = $2, updated_by = $3, updated_at = now()
WHERE id = $1
`

type RenameContentPageParams struct {
	ID        int64
	Slug      string
	UpdatedBy string
}

// Смена URL — только для черновиков (проверяется в сервисе).
func (q *Queries) RenameContentPage(ctx context.Context, arg RenameContentPageParams) error {
	_, err := q.db.Exec(ctx, renameContentPage, arg.ID, arg.Slug, arg.UpdatedBy)
	return err
}

const rescheduleOutbox = `-- name: RescheduleOutbox :exec
UPDATE outbox
SET attempts = attempts + 1, next_retry_at = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type RescheduleOutboxParams struct {
	ID          int64
	NextRetryAt pgtype.Timestamptz
	LastError   string
}

func (q *Queries) RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutbox, arg.ID, arg.NextRetryAt, arg.LastError)
	return err
}

const retryOrderDelivery = `-- name: RetryOrderDelivery :exec
UPDATE outbox
SET status = 'pending', next_retry_at = now(), last_error = '', updated_at = now()
WHERE kind = 'order'
  AND status = 'failed'
  AND (payload->>'order_id')::bigint = $1::bigint
`

func (q *Queries) RetryOrderDelivery(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, retryOrderDelivery, orderID)
	return err
}

const setContentPagePublished = `-- name: SetContentPagePublished :exec
UPDATE content_pages SET
    published = $2, indexed = content_pages.indexed OR $2,
    updated_by = $3, updated_at = now()
WHERE id = $1
`

type SetContentPagePublishedParams struct {
	ID        int64
	Published bool
	UpdatedBy string
}

// Публикация делает indexed=true липко (SEO-адрес закрепляется); снятие с
// публикации не сбрасывает indexed.
func (q *Queries) SetContentPagePublished(ctx context.Context, arg SetContentPagePublishedParams) error {
	_, err := q.db.Exec(ctx, setContentPagePublished, arg.ID, arg.Published, arg.UpdatedBy)
	return err
}

const updateBenefit = `-- name: UpdateBenefit :exec
UPDATE benefits SET
    icon = $2, title = $3, note = $4, href = $5, sort_order = $6, published = $7,
    updated_by = $8, updated_at = now()
WHERE id = $1
`

type UpdateBenefitParams struct {
	ID        int64
	Icon      string
	Title     string
	Note      string
	Href      string
	SortOrder int32
	Published bool
	UpdatedBy string
}

func (q *Queries) UpdateBenefit(ctx context.Context, arg UpdateBenefitParams) error {
	_, err := q.db.Exec(ctx, updateBenefit,
		arg.ID,
		arg.Icon,
		arg.Title,
		arg.Note,
		arg.Href,
		arg.SortOrder,
		arg.Published,
		arg.UpdatedBy,
	)
	return err
}

const updateContentPage = `-- name: UpdateContentPage :exec
UPDATE content_pages SET
    title = $2, body = $3, meta_title = $4, meta_description = $5,
    updated_by = $6, updated_at = now()
WHERE id = $1
`

type UpdateContentPageParams struct {
	ID              int64
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	UpdatedBy       string
}

func (q *Queries) UpdateContentPage(ctx context.Context, arg UpdateContentPageParams) error {
	_, err := q.db.Exec(ctx, updateContentPage,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.UpdatedBy,
	)
	return err
}

const updatePickupPoint = `-- name: UpdatePickupPoint :exec
UPDATE pickup_points SET
    slug = $2, address = $3, metro = $4, hours = $5, badge = $6, note = $7,
    is_central = $8, is_main = $9, city = $10, sort_order = $11, published = $12,
    updated_by = $13, updated_at = now()
WHERE id = $1
`

type UpdatePickupPointParams struct {
	ID        int64
	Slug      string
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	IsMain    bool
	City      string
	SortOrder int32
	Published bool
	UpdatedBy string
}

func (q *Queries) UpdatePickupPoint(ctx context.Context, arg UpdatePickupPointParams) error {
	_, err := q.db.Exec(ctx, updatePickupPoint,
		arg.ID,
		arg.Slug,
		arg.Address,
		arg.Metro,
		arg.Hours,
		arg.Badge,
		arg.Note,
		arg.IsCentral,
		arg.IsMain,
		arg.City,
		arg.SortOrder,
		arg.Published,
		arg.UpdatedBy,
	)
	return err
}

const updateProductImageClean = `-- name: UpdateProductImageClean :execrows
UPDATE products SET image_clean_url = $2 WHERE code = $1 AND code <> ''
`

type UpdateProductImageCleanParams struct {
	Code          string
	ImageCleanUrl string
}

func (q *Queries) UpdateProductImageClean(ctx context.Context, arg UpdateProductImageCleanParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProductImageClean, arg.Code, arg.ImageCleanUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSeoMeta = `-- name: UpdateSeoMeta :exec
UPDATE seo_meta SET
    title = $2, description = $3, updated_by = $4, updated_at = now()
WHERE route = $1
`

type UpdateSeoMetaParams struct {
	Route       string
	Title       string
	Description string
	UpdatedBy   string
}

// Правит только редактируемые поля (route/label/is_default не меняются из UI).
func (q *Queries) UpdateSeoMeta(ctx context.Context, arg UpdateSeoMetaParams) error {
	_, err := q.db.Exec(ctx, updateSeoMeta,
		arg.Route,
		arg.Title,
		arg.Description,
		arg.UpdatedBy,
	)
	return err
}

const upsertOverride = `-- name: UpsertOverride :exec
INSERT INTO product_overrides (slug, hidden, badge_hit, updated_by, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (slug) DO UPDATE
SET hidden = EXCLUDED.hidden,
    badge_hit = EXCLUDED.badge_hit,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertOverrideParams struct {
	Slug      string
	Hidden    bool
	BadgeHit  bool
	UpdatedBy *int64
}

func (q *Queries) UpsertOverride(ctx context.Context, arg UpsertOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertOverride,
		arg.Slug,
		arg.Hidden,
		arg.BadgeHit,
		arg.UpdatedBy,
	)
	return err
}

const upsertProduct = `-- name: UpsertProduct :exec

INSERT INTO products (
    code, slug, brand, model, name, size_label,
    width, profile, diameter, season, spikes, runflat,
    price, stock, image_url, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, now()
)
ON CONFLICT (code) WHERE code <> '' DO UPDATE SET
    slug = EXCLUDED.slug,
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    name = EXCLUDED.name,
    size_label = EXCLUDED.size_label,
    width = EXCLUDED.width,
    profile = EXCLUDED.profile,
    diameter = EXCLUDED.diameter,
    season = EXCLUDED.season,
    spikes = EXCLUDED.spikes,
    runflat = EXCLUDED.runflat,
    price = EXCLUDED.price,
    stock = EXCLUDED.stock,
    image_url = EXCLUDED.image_url,
    synced_at = now()
`

type UpsertProductParams struct {
	Code      string
	Slug      string
	Brand     string
	Model     string
	Name      string
	SizeLabel string
	Width     int32
	Profile   int32
	Diameter  int32
	Season    string
	Spikes    bool
	Runflat   bool
	Price     int32
	Stock     int32
	ImageUrl  string
}

// Upsert товара из синка SelectTyres (ключ — code). Динамические выборки каталога
// (листинг с фильтрами) идут сырым pgx через Filters.WhereSQL — здесь только статика.
func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.Exec(ctx, upsertProduct,
		arg.Code,
		arg.Slug,
		arg.Brand,
		arg.Model,
		arg.Name,
		arg.SizeLabel,
		arg.Width,
		arg.Profile,
		arg.Diameter,
		arg.Season,
		arg.Spikes,
		arg.Runflat,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	return err
}

const upsertProductOffer = `-- name: UpsertProductOffer :exec
INSERT INTO product_offers (product_code, city, price, stock, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (product_code, city) DO UPDATE SET
    price = EXCLUDED.price, stock = EXCLUDED.stock, updated_at = now()
`

type UpsertProductOfferParams struct {
	ProductCode string
	City        string
	Price       int64
	Stock       int32
}

// Цена/остаток товара в городе (мультигород). Ключ — (product_code, city).
func (q *Queries) UpsertProductOffer(ctx context.Context, arg UpsertProductOfferParams) error {
	_, err := q.db.Exec(ctx, upsertProductOffer,
		arg.ProductCode,
		arg.City,
		arg.Price,
		arg.Stock,
	)
	return err
}

const zeroStaleOffers = `-- name: ZeroStaleOffers :execrows
UPDATE product_offers SET stock = 0, updated_at = now()
WHERE updated_at < $1 AND stock <> 0
`

// Офферы, не обновлённые в текущем прогоне синка (товар пропал со складов города),
// гасим до нуля остатка. Строки не удаляем — заказы/URL могут ссылаться.
func (q *Queries) ZeroStaleOffers(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, zeroStaleOffers, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const zeroStaleStock = `-- name: ZeroStaleStock :execrows
UPDATE products SET stock = 0, synced_at = now()
WHERE code <> '' AND synced_at < $1 AND stock <> 0
`

// Товары, пропавшие из последней выгрузки, гасим до нуля остатка (не в наличии).
func (q *Queries) ZeroStaleStock(ctx context.Context, syncedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, zeroStaleStock, syncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
