// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	TokenHash string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type AdminUser struct {
	ID           int64
	Username     string
	PasswordHash string
	DisplayName  string
	CreatedAt    pgtype.Timestamptz
}

type Benefit struct {
	ID        int64
	Icon      string
	Title     string
	Note      string
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Href      string
}

type ContentPage struct {
	ID              int64
	Slug            string
	Title           string
	Body            string
	MetaTitle       string
	MetaDescription string
	Published       bool
	Indexed         bool
	System          bool
	UpdatedBy       string
	UpdatedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type Order struct {
	ID             int64
	IdempotencyKey string
	CustomerName   string
	Phone          string
	Comment        string
	Items          []byte
	Total          int32
	CreatedAt      pgtype.Timestamptz
}

type Outbox struct {
	ID          int64
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int32
	NextRetryAt pgtype.Timestamptz
	LastError   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Result      string
}

type PickupPoint struct {
	ID        int64
	Address   string
	Metro     string
	Hours     string
	Badge     string
	Note      string
	IsCentral bool
	SortOrder int32
	Published bool
	UpdatedBy string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Slug      string
	IsMain    bool
	City      string
}

type Product struct {
	ID            int64
	Slug          string
	Brand         string
	Model         string
	Name          string
	SizeLabel     string
	Width         int32
	Profile       int32
	Diameter      int32
	Season        string
	Spikes        bool
	Runflat       bool
	Price         int32
	Stock         int32
	SyncedAt      pgtype.Timestamptz
	Code          string
	ImageUrl      string
	ImageCleanUrl string
}

type ProductOffer struct {
	ProductCode string
	City        string
	Price       int64
	Stock       int32
	UpdatedAt   pgtype.Timestamptz
}

type ProductOverride struct {
	Slug      string
	Hidden    bool
	BadgeHit  bool
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *int64
}

type SeoMetum struct {
	Route       string
	Label       string
	Title       string
	Description string
	IsDefault   bool
	UpdatedBy   string
	UpdatedAt   pgtype.Timestamptz
}

type Wheel struct {
	ID         int64
	Code       string
	Slug       string
	Brand      string
	Model      string
	Name       string
	Category   string
	Width      float64
	Diameter   int32
	Pcd        string
	BoltsCount int32
	BoltsSpace float64
	Et         float64
	Dia        float64
	Color      string
	ColorHuman string
	WheelType  string
	ImageUrl   string
	Price      int64
	Stock      int32
	SyncedAt   pgtype.Timestamptz
}

type WheelOffer struct {
	WheelCode string
	City      string
	Price     int64
	Stock     int32
	UpdatedAt pgtype.Timestamptz
}
