// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wheel_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSyncedWheels = `-- name: CountSyncedWheels :one
SELECT count(*) FROM wheels WHERE code <> ''
`

func (q *Queries) CountSyncedWheels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSyncedWheels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWheelBySlug = `-- name: GetWheelBySlug :one
SELECT w.id, w.slug, w.code, w.brand, w.model, w.name, w.width, w.diameter,
       w.pcd, w.et, w.dia, w.color_human, w.wheel_type, wo.price, wo.stock, w.image_url
FROM wheels w
JOIN wheel_offers wo ON wo.wheel_code = w.code AND wo.city = $2
WHERE w.slug = $1
`

type GetWheelBySlugParams struct {
	Slug string
	City string
}

type GetWheelBySlugRow struct {
	ID         int64
	Slug       string
	Code       string
	Brand      string
	Model      string
	Name       string
	Width      float64
	Diameter   int32
	Pcd        string
	Et         float64
	Dia        float64
	ColorHuman string
	WheelType  string
	Price      int64
	Stock      int32
	ImageUrl   string
}

// City-aware: цена/остаток из оффера города ($2). Нет оффера в городе → нет строки.
func (q *Queries) GetWheelBySlug(ctx context.Context, arg GetWheelBySlugParams) (GetWheelBySlugRow, error) {
	row := q.db.QueryRow(ctx, getWheelBySlug, arg.Slug, arg.City)
	var i GetWheelBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Brand,
		&i.Model,
		&i.Name,
		&i.Width,
		&i.Diameter,
		&i.Pcd,
		&i.Et,
		&i.Dia,
		&i.ColorHuman,
		&i.WheelType,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
	)
	return i, err
}

const upsertWheel = `-- name: UpsertWheel :exec

INSERT INTO wheels (
    code, slug, brand, model, name, category, width, diameter, pcd,
    bolts_count, bolts_space, et, dia, color, color_human, wheel_type,
    image_url, price, stock, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, now()
)
ON CONFLICT (code) WHERE code <> '' DO UPDATE SET
    slug = EXCLUDED.slug, brand = EXCLUDED.brand, model = EXCLUDED.model,
    name = EXCLUDED.name, category = EXCLUDED.category, width = EXCLUDED.width,
    diameter = EXCLUDED.diameter, pcd = EXCLUDED.pcd, bolts_count = EXCLUDED.bolts_count,
    bolts_space = EXCLUDED.bolts_space, et = EXCLUDED.et, dia = EXCLUDED.dia,
    color = EXCLUDED.color, color_human = EXCLUDED.color_human, wheel_type = EXCLUDED.wheel_type,
    image_url = EXCLUDED.image_url, price = EXCLUDED.price, stock = EXCLUDED.stock,
    synced_at = now()
`

type UpsertWheelParams struct {
	Code       string
	Slug       string
	Brand      string
	Model      string
	Name       string
	Category   string
	Width      float64
	Diameter   int32
	Pcd        string
	BoltsCount int32
	BoltsSpace float64
	Et         float64
	Dia        float64
	Color      string
	ColorHuman string
	WheelType  string
	ImageUrl   string
	Price      int64
	Stock      int32
}

// Диски: upsert синком + мультигород-офферы. Динамический листинг — сырым pgx.
func (q *Queries) UpsertWheel(ctx context.Context, arg UpsertWheelParams) error {
	_, err := q.db.Exec(ctx, upsertWheel,
		arg.Code,
		arg.Slug,
		arg.Brand,
		arg.Model,
		arg.Name,
		arg.Category,
		arg.Width,
		arg.Diameter,
		arg.Pcd,
		arg.BoltsCount,
		arg.BoltsSpace,
		arg.Et,
		arg.Dia,
		arg.Color,
		arg.ColorHuman,
		arg.WheelType,
		arg.ImageUrl,
		arg.Price,
		arg.Stock,
	)
	return err
}

const upsertWheelOffer = `-- name: UpsertWheelOffer :exec
INSERT INTO wheel_offers (wheel_code, city, price, stock, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (wheel_code, city) DO UPDATE SET
    price = EXCLUDED.price, stock = EXCLUDED.stock, updated_at = now()
`

type UpsertWheelOfferParams struct {
	WheelCode string
	City      string
	Price     int64
	Stock     int32
}

func (q *Queries) UpsertWheelOffer(ctx context.Context, arg UpsertWheelOfferParams) error {
	_, err := q.db.Exec(ctx, upsertWheelOffer,
		arg.WheelCode,
		arg.City,
		arg.Price,
		arg.Stock,
	)
	return err
}

const zeroStaleWheelOffers = `-- name: ZeroStaleWheelOffers :execrows
UPDATE wheel_offers SET stock = 0, updated_at = now()
WHERE updated_at < $1 AND stock <> 0
`

func (q *Queries) ZeroStaleWheelOffers(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, zeroStaleWheelOffers, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const zeroStaleWheels = `-- name: ZeroStaleWheels :execrows
UPDATE wheels SET stock = 0, synced_at = now()
WHERE code <> '' AND synced_at < $1 AND stock <> 0
`

func (q *Queries) ZeroStaleWheels(ctx context.Context, syncedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, zeroStaleWheels, syncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
